#!/usr/bin/bash
rm -rf .terraform .terraform.lock.hcl terraform.tfstate terraform.tfstate.backup
terraform init terraform/build-image && terraform apply --auto-approve terraform/build-image && terraform init terraform/run-container && terraform apply --auto-approve terraform/run-container